--liquibase formatted sql

--changeset your.name:4
CREATE TABLE TA_BOOK_AUTHORS (
  BOOK_ID   INT NOT NULL, 
  AUTHOR_ID INT NOT NULL
);

CREATE UNIQUE INDEX XPKTA_BOOK_AUTHORS ON TA_BOOK_AUTHORS (BOOK_ID, AUTHOR_ID);

ALTER TABLE TA_BOOK_AUTHORS ADD CONSTRAINT XPKTA_BOOK_AUTHORS PRIMARY KEY (BOOK_ID, AUTHOR_ID);

CALL SYSPROC.ADMIN_CMD ( 'RUNSTATS ON TABLE TA_BOOK_AUTHORS ON ALL COLUMNS SET PROFILE' );

