CREATE OR REPLACE VIEW V_DATABASECHANGELOG AS 
SELECT CAST(ID AS VARCHAR(10)) AS ID, CAST(STRRIGHT(AUTHOR,15) AS VARCHAR(15)) AS AUTHOR, CAST(STRRIGHT(FILENAME,30) AS VARCHAR(30)) AS FILENAME, CAST(DATEEXECUTED AS DATE) AS DATEEXECUTED, ORDEREXECUTED, CAST(DESCRIPTION AS VARCHAR(10)) AS DESCRIPTION, CAST(COMMENTS AS VARCHAR(10)) AS COMMENTS, CAST(TAG AS VARCHAR(10)) AS TAG, CAST(CONTEXTS AS VARCHAR(10)) AS CONTEXTS, CAST(LABELS AS VARCHAR(10)) AS LABELS 
FROM DATABASECHANGELOG;

